version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest  # Replace with the correct image
    ports:
      - "11434:11434"
